### ISSUE TITLE
Greedy build key binding

### ISSUE THREAD

**Issue by fredrikpaues** [jaumefontal/SASS-Build-SublimeText2#30]
Hi! When I edit a .tex (LaTeX) file in Sublime 3083 on Windows 10 and press Ctrl+B (for build), Sass Build starts trying to build the file, even though it is clearly not a SASS file. Have you by any chance set key bindings in an overly greedy fashion? Perhaps without context sensitivity?

**Comment by alexlitel** [comment]
@fredrikpaues Sass Build doesn't set any key bindings on its own—it's literally just a Build System file. It sounds like you might have not set the Build System correctly—did you have the setting under `Tools > Build System` set to either 'Automatic' or 'SASS' or 'Sass — Compressed'?

**Comment by fredrikpaues** [comment]
That was it. My bad! Thanks!
